---
Only:
  moduleexists: 'silvercommerce/catalogue-admin'
---
DFT\SilverStripe\CataloguePage\Model\CataloguePage:
  product_class: 'Product'
  category_class: 'Category'

---
Only:
  moduleexists: 'silvercommerce/catalogue-frontend'
---
DFT\SilverStripe\CataloguePage\Model\CataloguePage:
  base_product_controller: 'ProductController'

---
Only:
  moduleexists: wilr/silverstripe-googlesitemaps
---
SilverCommerce\CatalogueAdmin\Model\CatalgoueProduct:
  extensions:
    - Wilr\GoogleSitemaps\Extensions\GoogleSitemapExtension

SilverCommerce\CatalogueAdmin\Model\CatalogueCategory:
  extensions:
    - Wilr\GoogleSitemaps\Extensions\GoogleSitemapExtension