---
Name: cataloguepageconfig
---
CatlalogueCategory:
  extensions:
    - CataloguePageCatalogueExtension
CatalogueProduct:
  extensions:
    - CataloguePageCatalogueExtension
    - CataloguePageProductExtension
